In [5]:
import numpy as np

In [6]:
a = np.arange(3)
print(a)


[0 1 2]


In [7]:
a = a + 5
print(a)

[5 6 7]


In [15]:
b = np.ones((3,3),dtype=int)
print(b)
print(a*b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[5 6 7]
 [5 6 7]
 [5 6 7]]


In [26]:
c = np.arange(3)
print(c)
d= np.reshape(c ,(3,1))
print(d)

[0 1 2]
[[0]
 [1]
 [2]]


In [27]:
print(c+d)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
