In [23]:
import numpy as np
import pandas as pd 

In [15]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [16]:
a = np.sum(a)
a


np.int64(15)

In [17]:
massive_array = np.random.random((1000))
massive_array

array([7.36771167e-01, 4.34262890e-01, 7.01865835e-01, 8.79857824e-01,
       6.72633705e-01, 3.47086024e-01, 3.81928146e-01, 9.58818273e-01,
       6.32917788e-02, 5.79665300e-02, 8.84996273e-02, 8.33924668e-01,
       4.53259699e-01, 1.80900047e-01, 3.78618719e-01, 1.07920807e-01,
       2.87851225e-02, 1.69689241e-01, 8.66740562e-01, 8.96270732e-01,
       9.22129933e-01, 1.99361201e-01, 1.19197047e-01, 7.65175021e-01,
       5.10433333e-01, 8.37707135e-01, 2.21254799e-01, 4.74697385e-01,
       4.91114435e-01, 2.68781210e-01, 2.60715958e-01, 4.27621652e-01,
       1.99651913e-01, 2.90376813e-01, 2.48192895e-01, 7.17871361e-01,
       3.86710065e-01, 4.98800458e-01, 5.97014563e-01, 9.85666425e-01,
       1.47420934e-01, 6.37923964e-01, 6.47967294e-01, 6.57273685e-02,
       1.76157507e-01, 7.70904620e-01, 7.67329932e-02, 1.76444682e-01,
       2.68536405e-01, 9.92935694e-01, 2.91652184e-01, 9.65830022e-01,
       4.63034491e-01, 4.96493798e-01, 3.80845322e-01, 5.20936186e-02,
      

In [19]:
examp = np.array([
    [10,20,30,40],
[1,2,3,4]])

In [21]:
print (examp)

[[10 20 30 40]
 [ 1  2  3  4]]


In [27]:
examp2 = pd.DataFrame(examp , columns = ["T2" , "T3" , "T4","T5"] , 
                      index = [ "tổng" , "số lượng"]

                      )

In [28]:
print(examp2)

          T2  T3  T4  T5
tổng      10  20  30  40
số lượng   1   2   3   4
