In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array([3.14 , 1 , 2 , 45])

array([ 3.14,  1.  ,  2.  , 45.  ])

In [4]:
np.array([3.94 , 8 , 5 , 6],dtype='int64')

array([3, 8, 5, 6])

In [11]:
a1 = np.array([[1,2,3,],[4,5,6]])

In [12]:
a1.shape

(2, 3)

In [14]:
a1.dtype

dtype('int64')

In [15]:
a1.size

6