create numpy array from scratch
+ zeros
+ one 
+ full
+ arange 
+ linspace

In [20]:
import numpy as np

In [21]:
np.array([1,2,3,4,5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
np.zeros([2,3],dtype = int , order="f")

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones([2,3],dtype=int,order="c")

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
a1 = np.array([[1,2,3],
              [4,5,6]])
a2 = np.array([[1,2,3],
              [4,5,6]])
print("a1:" , a1.flatten(order="c"))
print("a2:" , a2.flatten(order="f"))


a1: [1 2 3 4 5 6]
a2: [1 4 2 5 3 6]


In [25]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.full([3,5] , 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [34]:
np.linspace(0,2,5,dtype = float)

array([0. , 0.5, 1. , 1.5, 2. ])