# function random

In [3]:
import numpy as np


In [6]:
np.random.random([4,4])

array([[0.73443065, 0.37983581, 0.98578694, 0.67983802],
       [0.79389761, 0.21173504, 0.22626311, 0.4590831 ],
       [0.31149022, 0.95661434, 0.4800177 , 0.16583493],
       [0.97487216, 0.5567043 , 0.76656499, 0.73394997]])

In [12]:
np.random.seed(0)
np.random.random([4,4])


array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [ ]:
#deviation
np.random.normal(0 , 1 , (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [17]:
np.random.randint(0,100,[2,2]) 

array([[42, 58],
       [31,  1]], dtype=int32)