In [66]:
import numpy as np

In [67]:
# array indexing and silicing

In [68]:
x1 = np.random.randint(20,size = 6)

In [69]:
x1

array([11, 13,  2,  2,  9, 18], dtype=int32)

In [70]:
x1[2]

np.int32(2)

In [71]:
x1[:6]

array([11, 13,  2,  2,  9, 18], dtype=int32)

In [72]:
x1 = np.random.randint(20 ,size =  [3,4])

In [73]:
x1

array([[17,  5,  0,  2],
       [13, 18, 12, 17],
       [ 7,  6,  2, 19]], dtype=int32)

In [74]:
x1[1]

array([13, 18, 12, 17], dtype=int32)

In [75]:
x1[1,2] = 6

In [76]:
x1

array([[17,  5,  0,  2],
       [13, 18,  6, 17],
       [ 7,  6,  2, 19]], dtype=int32)

slicing

x1

In [77]:
x1

array([[17,  5,  0,  2],
       [13, 18,  6, 17],
       [ 7,  6,  2, 19]], dtype=int32)

In [78]:
x1[:2 ,:2]

array([[17,  5],
       [13, 18]], dtype=int32)

reshaping of arrays and transpose

In [79]:
x1 = np.arange(1,10)


In [80]:
x1.shape



(9,)

In [81]:
x2 = np.array([1,2,3,4,5,6,7,8])

In [82]:
x2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
x2.shape

(8,)

In [85]:
x2.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Array concatenation and splitting

In [88]:
x3 = np.array([1,2,3])
x4 = np.array([4,5,6]) 

In [90]:
np.concatenate((x3,x4))

array([1, 2, 3, 4, 5, 6])

In [91]:
x5 = np.array([[1,2,3,4],[5,6,7,8]])
x5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
np.concatenate(x5)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
np.concatenate((x5,x5), axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
np.concatenate((x5,x5), axis = 1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])